### ISSUE TITLE
找了很久这种有混合模式的轮播图，多谢了！

### ISSUE THREAD

**Issue by CoderKingXY** [LuKane/KNBannerView#4]
项目需求，有的图是带 url 的，有的是直接传入 UIImage 的。我又没时间写，刚好找到这个框架。写的不错，支持一下。
不过有个问题，就是我不需要创建的时候就把数据传入。我看你的数据源都是只读的。
有时候需要先创建出来。在某个特定的时候给数据源赋值，然后显示轮播。

**Comment by tqhy8899** [comment]
有个bug，就是如果网络图片不是五个，比如只有三个的时候，pagecontoller走到第三个的时候不会跳转到第一个，而是再走两次才会跳转到第一个。

**Comment by LuKane** [comment]
请问是  混合图片的界面吗？

**Comment by tqhy8899** [comment]
setupNetWorkBannerView3，在KNNetworkController里面的   网络图片 不是混合图片  混合的没试过

**Comment by LuKane** [comment]
好的,我尽快处理

**Comment by LuKane** [comment]
问题已经解决..请您更新最新的Demo

**Comment by tqhy8899** [comment]
嗯，好的




发自网易邮箱大师
在2016年12月01日 13:08，LuKane 写道:

问题已经解决..请您更新最新的Demo
