### ISSUE TITLE
挺好用的框架, 请问什么时候支持cocoapods

### ISSUE THREAD

**Issue by xiky** [LuKane/KNBannerView#5]
挺好用的框架, 请问什么时候支持cocoapods

**Comment by LuKane** [comment]
看看这段时间吧.... 如果可以就弄上去.

**Comment by LuKane** [comment]
我试了一下,自己电脑装不上 pods, 实在没法, 不好意思

**Comment by LuKane** [comment]
目前已经支持 cocoapods 了... 指定版本 : 2.0.1 , 对应适配的是 SDWebimage 5.0
